[project]
name = "project07"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agents>=1.4.0",
    "openai-agents>=0.2.8",
    "python-decouple>=3.8",
    "tensorflow-probability>=0.25.0",
]
