[project]
name = "project03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent>=0.1.3",
    "nest-asyncio>=1.6.0",
    "openai>=1.97.0",
    "openai-agents>=0.2.1",
    "python-decouple>=3.8",
]
